### ISSUE TITLE
running in openhabian, it keeps showing de adb help options

### ISSUE THREAD

**Issue by cavamora** [mattgyver83/adbee#1]
tried ./adbee.sh -d 192.168.0.18 -s sleep
and ./adbee.sh -ha -a com.netflix.ninja

it returns:
connected to 192.168.0.18:5555
Android Debug Bridge version 1.0.31

 -a                            - directs adb to listen on all interfaces for a connection
 -d                            - directs command to the only connected USB device
...

**Comment by mattgyver83** [comment]
I cant seem to replicate this; can you enable debugging and post the output?

./adbee.sh -g -d 192.168.0.18 -s sleep

Lets start there then we can look at opening netflix but I have some assumptions on that.  For what its worth this script was written for the firetv several versions ago before it had built in Alexa+FireTV support however it should still function as I still heavily use it with OpenHAB (and now Home Assistant).

**Comment by mattgyver83** [comment]
Closing, user either resolved, quit, or died tragically.
